services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sp-api-backend-dev
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=sqlite:///./listings.db
      - RELOAD=true
    volumes:
      - ./backend:/app
      - backend_data_dev:/app/sessions
    networks:
      - sp-api-network-dev
    restart: unless-stopped
    command: [ "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload" ]
    healthcheck:
      test: [ "CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: sp-api-frontend-dev
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - sp-api-network-dev
    restart: unless-stopped
    command: [ "npm", "run", "dev", "--", "--host", "0.0.0.0" ]

volumes:
  backend_data_dev:
    driver: local

networks:
  sp-api-network-dev:
    driver: bridge
